"
" General
"

let mapleader="\\"

set nobackup
set nowritebackup

" plugin things
filetype plugin on
filetype indent on

" set lines to the cursor
set so=7

" numbers
set nu
set rnu

" show where pattern is while typing
set incsearch

" Indent stuff
set shiftwidth=4
set tabstop=4

set autoindent
set smartindent
set wrap

"
" Pretty/Looks
"

syntax on
try
	colorscheme lunaperche
catch
endtry

set background=dark

" show whitespace
set listchars=tab:>\ ,trail:~
set list

"
" This code was generated by Gemini
"
augroup DynamicLeadMultispace
	autocmd!
	" Triggers when opening a file, switching buffers, or changing filetypes
	autocmd BufEnter,Filetype * call SetLeadMultispace()
augroup END

function! SetLeadMultispace()
	" Get the current indentation width (shiftwidth)
	let l:sw = shiftwidth()

	if l:sw > 0
		" Create a string with '+' followed by (sw - 1) spaces
		let l:lead = "+" . repeat(" ", l:sw - 1)

		" Dynamically update listchars for the current buffer
		" we use 'execute' because leadmultispace contains spaces
		execute "setlocal listchars+=leadmultispace:" . escape(l:lead, ' ')
	endif
endfunction

"
" Remaps/Keybinds
"

nnoremap R gR

"
" LSPs
"	:LspEnable
"	:LspInstallServer
"
"	Plugins:
"		git clone https://github.com/prabirshrestha/vim-lsp.git ~/.vim/pack/lsp/start/vim-lsp
"		git clone https://github.com/mattn/vim-lsp-settings.git ~/.vim/pack/lsp/start/vim-lsp-settings
"

" Don't auto enable
let g:lsp_auto_enable = 0
let g:lsp_settings_enable_autostart = 0

" Don't install LSPs automatically
let g:lsp_settings_enable_suggestions = 0
let g:lsp_settings_enable_install_server = 0

" Diagnostics
let g:lsp_diagnostics_enabled = 1
let g:lsp_signs_enabled = 1
let g:lsp_diagnostics_virtual_text_enabled = 0
let g:lsp_diagnostics_echo_cursor = 1
let g:lsp_diagnostics_float_cursor = 0
let g:lsp_diagnostics_highlights_enabled = 1

" Other
let g:lsp_preview_float = 1

" Enable and Disable
function! s:on_lsp_buffer_enabled() abort
	call lsp#enable()
	set signcolumn=yes

	" Remaps
	setlocal omnifunc=lsp#complete
	nmap gd <plug>(lsp-definition)
	nmap gr <plug>(lsp-rename)
	nmap K <plug>(lsp-hover)
	nmap [d <plug>(lsp-previous-diagnostic)
	nmap ]d <plug>(lsp-next-diagnostic)
endfunction

function! s:on_lsp_buffer_disable() abort
	call lsp#disable()
	set signcolumn=no

	" Remaps
	setlocal omnifunc=
	silent! nunmap gd
	silent! nunmap gr
	silent! nunmap K
	silent! nunmap [d
	silent! nunmap ]d

	" clean lsp diagnostics to fix highlighting issues
	if exists('*lsp#ui#vim#diagnostics#clear')
		call lsp#ui#vim#diagnostics#clear()
	endif
endfunction

" Manual enableage
command! EnableLsp call s:on_lsp_buffer_enabled()
command! DisableLsp call s:on_lsp_buffer_disable()


