"
" General
"

let mapleader=","

set nobackup
set nowritebackup

set undofile
set undodir=$HOME/.vim/vimundo

" plugin things
filetype plugin on
filetype indent on

" set lines to the cursor
set so=7

" numbers
set nu
set rnu

" show where pattern is while typing
set incsearch

set hls

" Indent stuff
set shiftwidth=4
set tabstop=4
set softtabstop=4

set autoindent
set smartindent
set wrap

set cc=80

"
" Pretty/Looks
"

syntax on
try
	"colorscheme lunaperche
	colorscheme darkblue
catch
endtry

set background=dark

" show whitespace
set listchars=tab:>\ ,trail:~
set list

"
" This code was generated by Gemini
"
augroup DynamicLeadMultispace
	autocmd!
	" Triggers when opening a file, switching buffers, or changing filetypes
	autocmd BufEnter,Filetype * call SetLeadMultispace()
augroup END

function! SetLeadMultispace()
	" Get the current indentation width (shiftwidth)
	let l:sw = shiftwidth()

	if l:sw > 0
		" Create a string with '+' followed by (sw - 1) spaces
		let l:lead = "+" . repeat(" ", l:sw - 1)

		" Dynamically update listchars for the current buffer
		" we use 'execute' because leadmultispace contains spaces
		execute "setlocal listchars+=leadmultispace:" . escape(l:lead, ' ')
	endif
endfunction

