"
" General
"

let mapleader=","

set nobackup
set nowritebackup

set undofile
set undodir=$HOME/.vim/vimundo

" plugin things
filetype plugin on
filetype indent on

" set lines to the cursor
set so=7

" numbers
set nu
set rnu

" show where pattern is while typing
set incsearch

set hls

" Indent stuff
set shiftwidth=4
set tabstop=4
set softtabstop=4

set autoindent
set smartindent
set wrap

set cc=80

"
" Pretty/Looks
"

syntax on
try
	"colorscheme lunaperche
	colorscheme darkblue
catch
endtry

set background=dark

" show whitespace
set listchars=tab:>\ ,trail:~
set list

"
" This code was generated by Gemini
"
augroup DynamicLeadMultispace
	autocmd!
	" Triggers when opening a file, switching buffers, or changing filetypes
	autocmd BufEnter,Filetype * call SetLeadMultispace()
augroup END

function! SetLeadMultispace()
	" Get the current indentation width (shiftwidth)
	let l:sw = shiftwidth()

	if l:sw > 0
		" Create a string with '+' followed by (sw - 1) spaces
		let l:lead = "+" . repeat(" ", l:sw - 1)

		" Dynamically update listchars for the current buffer
		" we use 'execute' because leadmultispace contains spaces
		execute "setlocal listchars+=leadmultispace:" . escape(l:lead, ' ')
	endif
endfunction

"
" Commands
"

com VI vertical terminal

"
" Remaps/Keybinds
"

nnoremap R gR

"
" LSPs
"	:LspEnable
"	:LspInstallServer
"
"	Plugins:
"		git clone https://github.com/prabirshrestha/vim-lsp.git ~/.vim/pack/lsp/start/vim-lsp
"		git clone https://github.com/mattn/vim-lsp-settings.git ~/.vim/pack/lsp/start/vim-lsp-settings
"

" Don't install LSPs automatically
let g:lsp_settings_enable_suggestions = 0
let g:lsp_settings_enable_install_server = 0

" Diagnostics
let g:lsp_diagnostics_virtual_text_enabled = 0
let g:lsp_diagnostics_float_cursor = 1

" pulled from the documentation
function! s:on_lsp_buffer_enabled() abort
	setlocal omnifunc=lsp#complete
	setlocal signcolumn=yes
	if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
	nmap <buffer> gd <plug>(lsp-definition)
	nmap <buffer> gs <plug>(lsp-document-symbol-search)
	nmap <buffer> gS <plug>(lsp-workspace-symbol-search)
	nmap <buffer> gr <plug>(lsp-references)
	nmap <buffer> gi <plug>(lsp-implementation)
	nmap <buffer> g<C-t> <plug>(lsp-type-definition)
	nmap <buffer> <leader>re <plug>(lsp-rename)
	nmap <buffer> [g <plug>(lsp-previous-diagnostic)
	nmap <buffer> ]g <plug>(lsp-next-diagnostic)
	nmap <buffer> K <plug>(lsp-hover)
	nnoremap <buffer> <expr><Tab> lsp#scroll(+4)
	nnoremap <buffer> <expr><S-Tab> lsp#scroll(-4)

	let g:lsp_format_sync_timeout = 1000
	autocmd! BufWritePre *.rs,*.go call execute('LspDocumentFormatSync')

	" refer to doc to add more commands
endfunction

augroup lsp_install
	au!
	" call s:on_lsp_buffer_enabled only for languages that has the server registered.
	autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END

